/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package condoware.CondoWare;

/**
 *
 * @author joaop
 */
public class TelaDoSindico extends javax.swing.JFrame {

    /**
     * Creates new form TelaDoCondomino
     */
    private TelaDoSindico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private static TelaDoSindico telaSindicoUnic;
    public static TelaDoSindico getTelaSindicoUnic(){
        if(telaSindicoUnic == null){
            telaSindicoUnic = new TelaDoSindico();
        }
        return telaSindicoUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRegistarProblemas = new javax.swing.JButton();
        btGerenciarEspaços = new javax.swing.JButton();
        btDadosPessoais = new javax.swing.JButton();
        btGerenciarPortão = new javax.swing.JButton();
        btRegistrarVisitante = new javax.swing.JButton();
        bRegistrarEmpressas = new javax.swing.JButton();
        btGerenciarFuncionario = new javax.swing.JButton();
        btGerenciarCondomino = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Incial");

        btRegistarProblemas.setText("Registrar Problemas");

        btGerenciarEspaços.setText("Gerenciar Espaços");

        btDadosPessoais.setText("Dados Pessoais");

        btGerenciarPortão.setText("Gerenciar Portão");

        btRegistrarVisitante.setText("Registrar Visitante");

        bRegistrarEmpressas.setText("Registrar Empresas");

        btGerenciarFuncionario.setText("Gerenciar Funcionario");

        btGerenciarCondomino.setText("Gerenciar Condômino");
        btGerenciarCondomino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarCondominoActionPerformed(evt);
            }
        });

        jButton1.setText("Empresas Parceiras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bRegistrarEmpressas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRegistarProblemas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerenciarEspaços, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDadosPessoais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerenciarPortão, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRegistrarVisitante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerenciarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerenciarCondomino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btDadosPessoais)
                .addGap(18, 18, 18)
                .addComponent(btGerenciarEspaços)
                .addGap(18, 18, 18)
                .addComponent(btRegistarProblemas)
                .addGap(18, 18, 18)
                .addComponent(btGerenciarPortão)
                .addGap(18, 18, 18)
                .addComponent(btRegistrarVisitante)
                .addGap(18, 18, 18)
                .addComponent(bRegistrarEmpressas)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btGerenciarFuncionario)
                .addGap(18, 18, 18)
                .addComponent(btGerenciarCondomino)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerenciarCondominoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarCondominoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarCondominoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EmpresasParceiras.getEmpresasParceirasUnic().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoSindico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoSindico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoSindico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoSindico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoSindico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegistrarEmpressas;
    private javax.swing.JButton btDadosPessoais;
    private javax.swing.JButton btGerenciarCondomino;
    private javax.swing.JButton btGerenciarEspaços;
    private javax.swing.JButton btGerenciarFuncionario;
    private javax.swing.JButton btGerenciarPortão;
    private javax.swing.JButton btRegistarProblemas;
    private javax.swing.JButton btRegistrarVisitante;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
